apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "next-js"
  name: "next-js"
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: "next-js"
  type: "NodePort"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "next-js"
  labels:
    app: next-js
spec:
  replicas: 1
  selector:
      matchLabels:
        app: "next-js"
  template:
    metadata:
      labels:
        app: next-js
    spec:
      containers:
        - name: "next-js"
          image: "vipdipp/nextjs-docker"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
